services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]

    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: winimarket_app.settings.prod
      POSTGRES_DB: winimarket
      POSTGRES_USER: wini_user
      POSTGRES_PASSWORD: wini@asay.get
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: winimarket
      POSTGRES_USER: wini_user
      POSTGRES_PASSWORD: wini@asay.get

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "-A", "winimarket_app", "worker", "--loglevel=info"]
    restart: always
    depends_on:
      - db
      - redis
    environment:
      PYTHONPATH: /code/winimarket_app
      DJANGO_SETTINGS_MODULE: winimarket_app.settings.prod
      POSTGRES_DB: winimarket
      POSTGRES_USER: wini_user
      POSTGRES_PASSWORD: wini@asay.get
      REDIS_HOST: redis

  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"