# Generated by Django 5.2.5 on 2026-02-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['-uploaded_at'], name='products_pr_uploade_66436c_idx'),
        ),
    ]
