# Generated by Django 5.2.5 on 2026-04-22 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_options_and_more'),
        ('registration', '0005_remove_selleraddress_campus_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_clicks', to='registration.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='registration.sellerprofile')),
            ],
        ),
    ]
