# Generated by Django 5.2.5 on 2026-06-26 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_contactclick'),
        ('registration', '0006_alter_sellerprofile_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to='registration.profile')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='products_pr_viewed__fd77c9_idx'), models.Index(fields=['product'], name='products_pr_product_e64eea_idx'), models.Index(fields=['user'], name='products_pr_user_id_0ed8b1_idx'), models.Index(fields=['session_key'], name='products_pr_session_5a3656_idx')],
            },
        ),
    ]
