# Generated by Django 5.2.5 on 2026-01-13 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customuser_options_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='registration.sellerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'event'], name='registratio_seller__48139b_idx'), models.Index(fields=['user'], name='registratio_user_id_d0721f_idx')],
            },
        ),
    ]
