# Generated by Django 5.2.5 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_sellernotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayment',
            name='service_provider',
            field=models.CharField(default='MTN Mobile Money', help_text='MTN Mobile Money / Vodafone Cash / AirtelTigo Money', max_length=20),
        ),
    ]
