# Generated by Django 5.2.5 on 2025-08-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_created_at_sellerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
    ]
