# Generated by Django 5.2.5 on 2026-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_sellerpayment_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraddress',
            name='campus_area',
        ),
        migrations.RemoveField(
            model_name='selleraddress',
            name='hall_or_hostel',
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='institution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='selleraddress',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
