# Generated by Django 5.2.5 on 2026-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_selleraddress_campus_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
