# Generated by Django 5.2.5 on 2025-12-07 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='verification_status',
            new_name='is_blacklisted',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='momo_details',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin'), ('support', 'Support')], default='buyer', max_length=10),
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='registration.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SellerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('momo_name', models.CharField(max_length=255)),
                ('momo_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registration.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_card', models.ImageField(upload_to='verification/id_cards/')),
                ('business_certificate', models.ImageField(blank=True, null=True, upload_to='verification/certificates/')),
                ('selfie_with_id', models.ImageField(upload_to='verification/selfies/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='registration.sellerprofile')),
            ],
        ),
    ]
