# Generated by Django 5.2.5 on 2025-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_verification_status_sellerprofile_is_blacklisted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerverification',
            old_name='id_card',
            new_name='id_card_image',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='business_certificate',
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='id_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='id_type',
            field=models.CharField(choices=[('student_id', 'Student ID'), ('ghana_card', 'Ghana Card')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
