# Generated by Django 5.2.5 on 2025-12-13 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_id_card_sellerverification_id_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sellerverification',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='SellerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('blacklisted', 'Blacklisted'), ('unblacklisted', 'Unblacklisted')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='registration.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
