# Generated by Django 5.2.5 on 2025-12-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_customuser_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
