# Generated by Django 5.2.5 on 2026-01-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_profile_role_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='campus',
            field=models.CharField(default='UEW - Winneba', max_length=100),
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='campus_area',
            field=models.CharField(default='North Campus', help_text='North Campus / South Campus / Central Campus', max_length=100),
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='hall_or_hostel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='landmark',
            field=models.CharField(blank=True, help_text='Near SRC, Opposite Library, etc.', max_length=255, null=True),
        ),
    ]
