# Generated by Django 5.2.5 on 2026-01-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('registration', '0002_alter_customuser_options_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_created_3cbaa0_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_order_created_ffede0_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('buyer', 'seller'), name='one_pending_order_per_buyer_seller'),
        ),
    ]
