# Generated by Django 5.2.5 on 2025-12-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
