# Generated by Django 5.2.5 on 2025-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(related_name='payment', to='order.order'),
        ),
    ]
