# Generated by Django 5.2.5 on 2025-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_payment_order_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(related_name='payments', to='order.order'),
        ),
    ]
