# Generated by Django 5.2.5 on 2025-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
