# Generated by Django 5.2.5 on 2026-01-07 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='Email event type e.g. order_paid, order_shipped', max_length=50)),
                ('recipient_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Email Log',
                'verbose_name_plural': 'Order Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'event', 'recipient_email'], name='order_order_order_i_3f081c_idx')],
            },
        ),
    ]
