[uwsgi]
# Bind to the Cloud Run port
http = :$(PORT)

# Point to your Django app
chdir = /code/winimarket_app/
module = winimarket_app.wsgi:application

master = true
processes = 4
threads = 2

# Graceful shutdown and health
die-on-term = true
vacuum = true

# Logging
log-date = true
