[uwsgi]

# Cloud Run listens on 8080
http = :8080

# Correct Django project root
chdir = /code/winimarket_app
pythonpath = /code/winimarket_app

# Django WSGI app
module = winimarket_app.wsgi:application

master = true
processes = 2
threads = 4
enable-threads = true
single-interpreter = true

# Cloud Run graceful shutdown
die-on-term = true
harakiri = 120
max-requests = 1000
vacuum = true

# Logging
log-date = true
log-format = [uWSGI] %(method) %(uri) => %(status) in %(msecs) ms
logto = /dev/stdout
logto2 = /dev/stderr
log-level = debug
catch-exceptions = true
log-exceptions = true
